version: '3'
services:
  apache:
    build:
      context: './apache'
      dockerfile: 'Dockerfile-${PHP_VERSION}'
      args:
        - 'SERVER_ROOT=${SERVER_ROOT}'
        - 'PHP_VERSION=${PHP_VERSION}'
        - 'DISPLAY_PHPERROR=${DISPLAY_PHPERROR}'
        - 'MONGODB_VERSION=${MONGODB_VERSION}'
    volumes:
      - '${APP_CODE_PATH_HOST}:${APP_CODE_PATH_NGINX}${APP_CODE_CONTAINER_FLAG}'
    ports:
      - '${APACHE_HOST_HTTP_PORT}:80'
  mysql:
    build:
      context: './mysql'
    environment:
      - 'MYSQL_DATABASE=${DB_NAME}'
      - 'MYSQL_USER=${DB_USER}'
      - 'MYSQL_PASSWORD=${DB_PASSWORD}'
      - 'MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}'
    volumes:
      - '${DATA_PATH_HOST}/mysql:/app'
      - '${MYSQL_PATH}/my.cnf:/etc/mysql/my.cnf'
    ports:
      - '${MYSQL_PORT}:3306'
  phpmyadmin:
    build: './phpmyadmin'
    environment:
      - 'PMA_ARBITRARY=1'
      - 'MYSQL_USER=${DB_USER}'
      - 'MYSQL_PASSWORD=${DB_PASSWORD}'
      - 'MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}'
    ports:
      - '${PMA_PORT}:80'
volumes:
  phpmyadmin:
    driver: '${VOLUMES_DRIVER}'
