version: "3"
services:
  alpine_apache:
    build:
      context: "./alpine_apache"
      dockerfile: "Dockerfile-${PHP_VERSION}"
      args:
        - "SERVER_ROOT=${SERVER_ROOT}"
        - "PHP_VERSION=${PHP_VERSION}"
    volumes:
      - "${APP_CODE_PATH_HOST}:${APP_CODE_PATH_NGINX}${APP_CODE_CONTAINER_FLAG}"
    ports:
      - "${APACHE_HOST_HTTP_PORT}:80"
  alpine_mysql:
    image: "deckapp/mysql:v${AMYSQL_VERSION}"
    environment:
      - "MYSQL_DATABASE=${MYSQL_DATABASE}"
      - "MYSQL_USER=${MYSQL_USER}"
      - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
    volumes:
      - "${DATA_PATH_HOST}/mysql:/var/lib/mysql"
      - "${MYSQL_PATH}:/etc/mysql/"
    ports:
      - "${AMYSQL_PORT}:3306"
  phpmyadmin:
    build: "./phpmyadmin"
    environment:
      - "PMA_ARBITRARY=1"
      - "MYSQL_USER=${PMA_USER}"
      - "MYSQL_PASSWORD=${PMA_PASSWORD}"
      - "MYSQL_ROOT_PASSWORD=${PMA_ROOT_PASSWORD}"
    ports:
      - "${PMA_PORT}:80"
volumes:
  phpmyadmin:
    driver: "${VOLUMES_DRIVER}"
