FROM ghcr.io/deck-app/apache:v5.6
LABEL maintainer Naba Das <hello@get-deck.com>

RUN apk add --update --no-cache php5-xml
				 #add to extension (i.e. php5-fpm)

COPY php_ini/php5.6.ini /etc/php5/php.ini
ARG DISPLAY_PHPERROR
RUN if [ ${DISPLAY_PHPERROR} = true ]; then \
sed -i "s#{DISPLAY}#On#g" /etc/php5/php.ini \
;else \
sed -i "s#{DISPLAY}#Off#g" /etc/php5/php.ini \
;fi

RUN rm -Rf /var/www/*


COPY httpd.conf /etc/apache2/httpd.conf
ARG SERVER_ROOT
RUN sed -i "s#{SERVER_ROOT}#${SERVER_ROOT}#g" /etc/apache2/httpd.conf

ARG INSTALL_ADDITIONAL_EXTENSIONS
RUN if [ -z "$INSTALL_ADDITIONAL_EXTENSIONS" ] ; then \
echo "No additional PHP extensions added" \
;else \
apk add --no-cache ${INSTALL_ADDITIONAL_EXTENSIONS} \
;fi

WORKDIR /var/www
