FROM ghcr.io/deck-app/apache:v5.6
LABEL maintainer Naba Das <hello@get-deck.com>

#add to extension (i.e. php5-fpm)

COPY php_ini/php.ini /etc/php5/php.ini
ARG DISPLAY_PHPERROR
RUN if [ ${DISPLAY_PHPERROR} = true ]; then \
sed -i "s#{DISPLAY}#On#g" /etc/php5/php.ini \
;else \
sed -i "s#{DISPLAY}#Off#g" /etc/php5/php.ini \
;fi

RUN rm -Rf /var/www/*


COPY httpd.conf /etc/apache2/httpd.conf
ARG SERVER_ROOT
RUN sed -i "s#{SERVER_ROOT}#${SERVER_ROOT}#g" /etc/apache2/httpd.conf

ARG INSTALL_ADDITIONAL_EXTENSIONS
RUN if [ -z "$INSTALL_ADDITIONAL_EXTENSIONS" ] ; then \
echo "No additional PHP extensions added" \
;else \
apk add --no-cache ${INSTALL_ADDITIONAL_EXTENSIONS} \
;fi

#Xdebug enable or disable
ARG XDEBUG
RUN if [ ${XDEBUG} = true ]; then \
apk update && apk add --no-cache php5-xdebug \
&& echo "zend_extension=/usr/lib/php5/modules/xdebug.so" >> /etc/php5/php.ini \
;fi

WORKDIR /var/www
