FROM deckapp/apache:v7.0

# Persistent runtime dependencies
ARG DEPS="\
         #add to extension (i.e. php7-fpm \)
         php7-gd \
"

RUN set -x \
    && apk add --no-cache $DEPS

COPY httpd.conf /etc/apache2/httpd.conf
ARG SERVER_ROOT
RUN sed -i "s#{SERVER_ROOT}#$SERVER_ROOT#g" /etc/apache2/httpd.conf
VOLUME [ "/var/www/" ]
WORKDIR /var/www
COPY php_ini/php7.0.ini /etc/php7/php.ini

RUN ln -s /usr/bin/php7 /usr/bin/php
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer


ARG DISPLAY_PHPERROR
RUN if [ ${DISPLAY_PHPERROR} = true ]; then \
sed -i "s#{DISPLAY}#On#g" /etc/php7/php.ini \
;else \
sed -i "s#{DISPLAY}#Off#g" /etc/php7/php.ini \
;fi

#Xdebug enable or disable
ARG XDEBUG
RUN apk update
RUN if [ ${XDEBUG} = true ]; then \
apk add php7-xdebug \
;fi